version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_DEFAULT_THEME: vshn
      KEYCLOAK_WELCOME_THEME: vshn
    volumes:
      - ./theme:/opt/jboss/keycloak/themes/vshn:ro
      - ./disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli:ro
