services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    entrypoint: /opt/entrypoint.sh
    volumes:
      - ./theme:/opt/keycloak/themes/vshn:ro
      - ./keycloak/master.json:/opt/keycloak/data/import/master.json:ro
      - ./entrypoint.sh:/opt/entrypoint.sh:ro
  mailpit:
    image: axllent/mailpit:v1.26
    container_name: mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
