version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --debug
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --spi-theme-login-theme=vshn
    volumes:
      - ./theme:/opt/keycloak/themes/vshn:ro
