services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    entrypoint: /opt/entrypoint.sh
    volumes:
      - ./theme:/opt/keycloak/themes/vshn:ro
      - ./keycloak/master.json:/opt/keycloak/data/import/master.json:ro
      - ./entrypoint.sh:/opt/entrypoint.sh:ro
