services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    entrypoint: /opt/entrypoint.sh
    volumes:
      - ./theme:/opt/keycloak/themes/vshn:ro
      - ./keycloak/master.json:/opt/keycloak/data/import/master.json:ro
      - ./entrypoint.sh:/opt/entrypoint.sh:ro
